### ISSUE TITLE
Panic on Subtract overflow

### ISSUE THREAD

**Issue by Billy-Sheppard** [andrewbaxter/genemichaels#14]
`thread 'main' panicked at 'attempt to subtract with overflow', src/comments.rs:519:54`

This line panics on some files, unsure exactly what in the file causes it.

**Comment by andrewbaxter** [comment]
Ah, that was working around https://github.com/wooorm/markdown-rs/issues/38 but I guess it was leaky.  Supposedly it's been fixed so updating the library and removing the subtraction should fix it.

**Comment by andrewbaxter** [comment]
Fixed in 80127aa5117bd4d4dd3f9530eb0b463feac68fdf (messed up commit message)
