### ISSUE TITLE
Lex syn error on some files

### ISSUE THREAD

**Issue by Billy-Sheppard** [andrewbaxter/genemichaels#15]
`Error formatting {file}: Rendered document couldn't be re-parsed in verification step: {line}:0: lex error`

Unsure what causes this with some files - column always seems to be 0. In my testing one line was a method call, and another was a trait function definition.

**Comment by andrewbaxter** [comment]
Yeah, I'm not sure.  I'd guess that genemichaels is outputting bad rust code somewhere, but the syn error message isn't particularly verbose here.  Lex error suggests it can't turn the text into a known token, but that includes identifiers, and lexers are (typically?) non-context-sensitive so almost any text should be okay.

I'll try some other repos to see if I can find other code in the wild that shows this issue.

**Comment by andrewbaxter** [comment]
FWIW I tried a couple more repos and fixed some issues.  I didn't see this specifically, but it's possible this got fixed within that...

**Comment by Billy-Sheppard** [comment]
Funnily enough I'm seeing more `Error formatting file {file}: Rendered document couldn't be re-parsed in verification step: {line}:{col}: expected ` since that change...

**Comment by andrewbaxter** [comment]
Would you be able to show a couple lines before/after when that happens? It should print the (broken) formatted code before the error - the line numbers will be relevant to that dump (rather than the original source code).

**Comment by Billy-Sheppard** [comment]
An issue I've noticed - unsure if there are more because this seems to break it first: `async move` gets returned as `asyncmove`

**Comment by Billy-Sheppard** [comment]
Ex 1 (`Rendered document couldn't be re-parsed in verification step: 269:0: lex error`):
```rust
265 | // comment
263 | /// doc comment
264 | /// doc comment
265 | /// doc comment
266 | pub trait MyTrait {
267 |     // comment
268 |     // comment
269 |     type FileStruct: de::DeserializeOwned + Debug;
270 | 
271 |     fn function(file: impl io::Read) -> anyhow::Result<Vec<Self::FileStruct>> {
              .. 
279 |     }
```

Ex 2 (`Rendered document couldn't be re-parsed in verification step: 380:0: lex error`): 
```rust 
376 | info!("..{}", var1);
377 | let f = var2.method(param).await?;
378 | info!("..{}", var3);
379 | var4
380 |     .method(
381 |         &param,
382 |         &param2.method(file_name::Location::root()),
383 |         param3,
384 |         None,
385 |         None,
386 |     )
387 |     .await?;
388 | info!("..{}", var);
```

**Comment by andrewbaxter** [comment]
Weird, both of those look totally normal to me... not that I'm great at picking out source code errors. Those are from the blow eprintln post-format dump? Or are they from the original source?

FWIW It looks like it is covered, this is it here: https://github.com/andrewbaxter/genemichaels/blob/master/src/bin/genemichaels.rs#L159

**Comment by andrewbaxter** [comment]
Maybe rather than dump the whole broken-formatted code it should chop out the 5 lines before/after the error and just print that (with line numbers).  It'd be more obviously an error too...

**Comment by andrewbaxter** [comment]
I added this to make reparsing (verification) errors clearer, but I think the lex errors are pre-formatting possibly: https://github.com/andrewbaxter/genemichaels/pull/37

**Comment by Billy-Sheppard** [comment]
This seems to have been resolved, I am no longer seeing these errors.

**Comment by andrewbaxter** [comment]
Ah great! Well feel free to open a new issue too if it comes up again.  I didn't consciously fix this, but I did fix a few other issues here and there so maybe I got lucky...
