### ISSUE TITLE
Formatting Types with `(... ,)` removes the commma

### ISSUE THREAD

**Issue by Billy-Sheppard** [andrewbaxter/genemichaels#19]
Example:
```rust
warp::filters::BoxedFilter<(std::boxed::Box<dyn warp::Reply + 'a>,)>, // this
warp::filters::BoxedFilter<(std::boxed::Box<dyn warp::Reply + 'a>)>,  // to this, causes compiler error
```

Thank `warp`'s weird and wacky types :D

**Comment by andrewbaxter** [comment]
Right... per https://doc.rust-lang.org/stable/reference/expressions/tuple-expr.html this appears to be the one place in the language where a trailing comma is significant.  Might have to completely duplicate the formatting logic here but I guess that's how it goes.

**Comment by andrewbaxter** [comment]
```
fn main() {
    x((7,));
}
```
syn isn't parsing this for me, but it works fine in the rust playground. Need to investigate more.

**Comment by Billy-Sheppard** [comment]
Looks good! Cheers for fixing this, classic edge case!
