### ISSUE TITLE
Detect and shorthand fields

### ISSUE THREAD

**Issue by andrewbaxter** [andrewbaxter/genemichaels#4]
Per standard rust? warnings, `field: field` should probably be shortened to `field` by default.

**Comment by Billy-Sheppard** [comment]
I'm still getting this issue on `cargo install genemichaels v0.1.10`.

Specifically when pattern matching structs in code e.g.
```rust
fn my_function(
    MyStruct {
        my_field: my_field
    } : MyStruct
) {
  ..
}
```
and
```rust
match x {
    MyEnum::MyVariant {
        my_field: my_field
    } => { .. }
  ..
}
```
or even
```rust
if let Some(MyStruct {my_field: my_field}) = my_value { .. } else { .. };
```

**Comment by andrewbaxter** [comment]
Ah, good catch.  Yeah, that's handled by a separate part of the AST, probably need to do the same there.

**Comment by andrewbaxter** [comment]
As an aside, for now the fix above doesn't shorthand anything, it just keeps whether it was shorthanded or not from the syn ast (so if it was shorthand before, it stays shorthand).  I didn't want to touch this because it gets more complex if there are comments before/after the `:` which would have no place to go if it was shorthanded, although you could say it's less deterministic this way.

Probably a bridge I'll have to cross if I wanted to do stuff with single expr blocks `{}` and messing with `use ...` statements.
