### ISSUE TITLE
Prevent comment wrapping directly before punctuation

### ISSUE THREAD

**Issue by andrewbaxter** [andrewbaxter/genemichaels#48]
Like ,. after a `code` block, I think it's better to keep them on the same line even if they end up going over the character limit...

This is syntactically significant, since a newline will turn into a space during unwrapping.

**Comment by AaronKutch** [comment]
To be specific, if they go over the character limit then it drags the stuff it is "glued" to with it (except if the whole glued part is still over the character limit, rustfmt gives up and prints an error in such a case so that the user can decide where they can break it)? e.x.
```
// the limit is here ------v
// testing testing testing...
```
gets converted to
```
// the limit is here ------v
// testing testing
// testing...
```

**Comment by andrewbaxter** [comment]
> gets converted to
> 
> ```
> // the limit is here ------v
> // testing testing
> // testing...
> ```

FWIW this should already be fine, since there's only one element here (text).  It's only at the boundaries of different element types (plain text, inline code, bold, italics, etc) where the poor splitting occurs.  I think the main case you're seeing is inline code followed by plain text punctuation.

**Comment by AaronKutch** [comment]
oh that's what I'm seeing, thanks
