### ISSUE TITLE
`static mut` changed to just `static`

### ISSUE THREAD

**Issue by elfeiin** [andrewbaxter/genemichaels#73]
Formatting a file containing `static mut` removes the `mut`.

**Comment by andrewbaxter** [comment]
Thanks for the report! I'll try to fix this asap!

**Comment by andrewbaxter** [comment]
Published as `0.2.4`.  I want to tweak a couple other things but I figured I'd release this first.

**Comment by andrewbaxter** [comment]
Forgot to say, let me know if that didn't work or if you hit any other issues!
