### ISSUE TITLE
Detect and use workspaces

### ISSUE THREAD

**Issue by Billy-Sheppard** [andrewbaxter/genemichaels#8]
Would it be possible to add the ability for it to format an entire workspace when available?

I have been using `find . -name \*.rs -exec genemichaels {} \;` in lieu.

**Comment by andrewbaxter** [comment]
Ah, I've been doing that too :sweat_smile: 

That sounds reasonable... there's a crate for parsing the Cargo.toml file, and I guess we could use that to get workspace dirs and then just glob?

I'll need to figure out how Cargo.toml works better.

**Comment by Billy-Sheppard** [comment]
That sounds like a reasonable solution - this is a cool crate so I think its worth working through. I know `rust-fmt` has issues with workspaces... so this could be good.
