### ISSUE TITLE
`'lifetime: { ... }` becomes just `{ ... }`

### ISSUE THREAD

**Issue by elfeiin** [andrewbaxter/genemichaels#87]
It should keep the lifetime notation on blocks.

**Comment by andrewbaxter** [comment]
Thanks for the report! I'll take a look, probably in a few hours though.

**Comment by andrewbaxter** [comment]
Should be fixed in 3b240c34367ac90a9806209a31d44c0fd21a3873 - released as 0.3.3.  Let me know if that doesn't work!

And thanks again for making the issue!
