### ISSUE TITLE
`tab_spaces` setting?

### ISSUE THREAD

**Issue by xxshady** [andrewbaxter/genemichaels#91]
https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=#tab_spaces

**Comment by andrewbaxter** [comment]
Okay, I added this! Let me know if you have any issues with it.  The repo organization has changed a bit, but it's `indent_spaces` at https://github.com/andrewbaxter/genemichaels/blob/master/readme_genemichaels.md#configuration .
